### PR TITLE
Show full list of completions for Array/String/Number/Boolean/etc constructors

### PR DESCRIPTION
**Pull request by hoanhtien**
Fixes https://github.com/Microsoft/nodejstools/issues/192.

### CODE REVIEW

**Comment by kant2002** [comment]
When this would be added ?

**Comment by billti** [comment]
We were pretty conservative in taking changes while stabilizing for the final 1.1 release. I expect we'll start cleaning up the outstanding pull requests shortly. 

FYI: We've had a few folks out on training and vacation the past couple weeks, so progress has been a little slow.

**Comment by kant2002** [comment]
Could this be added, since 1.1 is released now?

**Comment by mjbvz** [comment]
@mousetraps Just looking through some of these outstanding pull requests. This one doesn't have any conflicts and the code looks good enough to me. Can you please take a quick look over it too so we can decide to either merge or close this PR?

**Pull request merged**
