### PR TITLE
Update Vue.js templates and packages

### PR DESCRIPTION
**Pull request by armanio123**
The Vue CLI 3 has been recently released. This PR is for updating the templates and package dependencies to match the cli templating.

### CODE REVIEW

**Comment by armanio123** [comment]
With the eslint support recently added, I have added the default Vue.js eslint support to the JavaScript template. Attached the zip files containing the working projects for JS and TS:

[TypeScript-VueTemplate.zip](https://github.com/Microsoft/nodejstools/files/2285171/TypeScript-VueTemplate.zip)
[JavaScript-VueTemplate.zip](https://github.com/Microsoft/nodejstools/files/2285172/JavaScript-VueTemplate.zip)

There's an eslint warning shown by VS that I'm already checking with @uniqueiniquity :
image

**Comment by uniqueiniquity** [comment]
@armanio123 To fix those warnings, explicitly add `eslint` to the `devDependencies` in the `package.json`. VS won't recognize that ESLint is locally installed unless the `package.json` acknowledges it.

**Comment by armanio123** [comment]
Thanks @uniqueiniquity for the input, I have added the eslint to the package as suggested and the warnings are now gone. Also as added back Babel to the TypeScript template.

This is how the templates look like now: [JS and TS Vue Templates.zip](https://github.com/Microsoft/nodejstools/files/2288293/JS.and.TS.Vue.Templates.zip)

**Comment by armanio123** [comment]
Mentioning @DanielRosenwasser @bowdenk7 for visibility.

**Pull request merged**
