### PR TITLE
Change dimensions and font size to improve appearance of general properties page in high dpi

### PR DESCRIPTION
**Pull request by anubmat**
Bug #1452 : General Properties page is hard to read in high dpi

### CODE REVIEW

**Comment by paulvanbrenk** [comment]
Can you add a screenshot on how this looks after your changes?

**Comment by anubmat** [comment]
This is how node project property page will look. In both cases text is big enough to read (looks small here). It will begin to look a little worse in Normal resolution, but will become readable in high-dpi. I adjusted locations and sizes a/c to high dpi. I think an improvement would be to have a table layout like TS, and make autoscalable columns.

Normal (1920X1080):
image

High dpi:
image

**Comment by paulvanbrenk** [comment]
Thanks, that looks pretty good.

**Comment by anubmat** [comment]
@RyanCavanaugh , can you help me check this in?

**Comment by RyanCavanaugh** [comment]
Thanks!

**Pull request merged**
