### PR TITLE
Updated package.json for test projects for compliance reasons

### PR DESCRIPTION
**Pull request by joj**
Most of the mock projects are fairly old, and they were triggering compliance checks. Updated packages to avoid this. This may fail tests. If it doesn't, we should consider removing these projects.

### CODE REVIEW

**Comment by armanio123** [comment]
Can we instead have an exception on the mock projects?

**Review by armanio123 — APPROVED** [review]

**Comment by joj** [comment]
What do you mean? Removing them completely?

**Comment by armanio123** [comment]
Sorry, no I mean an exception on the compliance check.

**Comment by joj** [comment]
That's a possibility, but I'd rather have all of our compliance be super accurate right now.

**Pull request merged**
