### PR TITLE
 Make the various Guids used in the debug engine unique from PTVS  

### LINKED ISSUE #147: Need to use a unique GUID for the DebugEngineAttribute
Product\SharedProjectProject\ProvideDebugEngineAttribute.cs.  The CLSID is the same as PTVS and is colliding in registry.  We need to use a unique GUID for this value.

### PR DESCRIPTION
**Pull request by paulvanbrenk**
Adds the debug guids to the central guid file, and ensures they're unique from the PTVS guids. 

Fixes #147

### CODE REVIEW

**Comment by mousetraps** [comment]
LGTM. Based on the change to CRLF, I assume you intentionally change the line endings on this one? 

https://github.com/Microsoft/nodejstools/pull/176/files?w=1 without line endings

**Comment by mousetraps** [comment]
Actually, one of the GUIDs is still the same: 
```
A241707C-7DB3-464F-8D3E-F3D33E86AE99
```

**Comment by paulvanbrenk** [comment]
Yes, the RemoteDebugPortSupplier is the same, that wasn't changed in PTVS either. and they don't collide. So I kep that the same.

**Comment by paulvanbrenk** [comment]
And VS changed the line endings for me..

**Pull request merged**
