### PR TITLE
Fix issues with building from source

### PR DESCRIPTION
**Pull request by kant2002**
This remove warning which prevent to perform build of MSI, See #891

### CODE REVIEW

**Comment by mjbvz** [comment]
@mousetraps Can you please take a look at this one.

**Comment by mousetraps** [comment]
This change has a good chance of breaking installations of NTVS on machines that do not have the VS SDK installed because required interop types are no longer being embedded. Instead, I believe the proper and less risky fix is to embed interop types on the Microsoft.VisualStudio.CommandBars reference instead. Could you try this and see how it goes?

Additionally, I can't reproduce this behavior at all. Could you specify some more details about your machine configuration? VS version / update #, etc? Which VS command prompt are you using? And presumably you're building from master?

**Comment by kant2002** [comment]
@mousetraps 
1. I build from master.
2. I have installed VS2013, VS2015 and VS15 Preview.
3. I use Git Shell form GitHub for Windows (which is basically Powershell + some adjustments)

I have to make MSbuild from VS2015 to path, in order to make a build.

If I understand correctly somehow references from VSN15 (Next) picked up instead of VS2015.

I run build like that:
`msbuild NodejsTools.sln /p:Configuration=Release /p:VsTarget=14.0 /p:VisualStudioVersion=14.0`

What I notice is just now is that in each project envdte used from VS15 folder, not VS2015.
In the project reference properties
Path = `C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\envdte.dll`
Instead of 

Path = `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PublicAssemblies\envdte.dll`

That's I see in MSBuild logs and inside VS 2015.

**Comment by mousetraps** [comment]
Okay, thanks for the additional info. I'll see if I can reproduce your environment when i get the chance - also did you try the fix suggested above?

**Comment by kant2002** [comment]
@mousetraps I try instead of that fix, just change `EmbedInteropTypes` to `True` for Microsoft.VisualStudio.CommandBars, but still no luck.

```
error CS1762 : Warning as error : A reference was created to embedded interop assembly 
'c:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\PublicAssemblies\envdte.dll' 
because of an indirect reference to that assembly created by assembly 
'c:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\VisualStudioIntegration\Common\Assemblies\v4.0\Microsoft.VisualStudio.Shell.14.0.dll'. 
Consider changing the 'Embed Interop Types' property on either assembly.
```

**Comment by kant2002** [comment]
Sorry for bothering, I do full clean and build working.

**Pull request closed without merging**
