### PR TITLE
Use appveyor.yaml for CI config

### PR DESCRIPTION
**Pull request by mjbvz**
This allows us to use some more fancy configuration options for CI.

Creates two configurations, one for master and one for v1.1.x. Master no longer builds VS12, but v1.1.x will

### CODE REVIEW

**Comment by mjbvz** [comment]
We will have to merge this into `v1.1.x` too. AppVeyor recommends that you use a common `appveyor.yml` across all branches to avoid merge conflicts.

**Comment by mjbvz** [comment]
Also, after this change, the AppVeyor UI settings will no longer do anything..

**Comment by mousetraps** [comment]
:+1: 

Regarding our earlier discussion... what happens in the event that we are locking down for a release and potentially submitting patches to a different branch? Do we need to add a new entry to the AppVeyor run every time?

**Comment by mjbvz** [comment]
@mousetraps Yes, but there are a few options in my understanding: 

* Before creating the new branch, update the `appveyor.yaml` to in the parent branch to reference the new branch as well. 
* Update the `appveyor.yaml` to use simple patterns for the branch name matching. That would allow us to build all `v1.x.x` branches for a given config.
* Create a fallback, default entry in the `appveyor.yaml` that builds any branch not explicitly matched.

# New branch creation process
If neither branch name glob matching or the fallback would work, and we instead want to make new branches fully opt-in, I believe that the steps to create a new branch would look somewhat like this (new branch is called `v2.7.1` and branched off of `master` and using its config in this example):

* In `master`, add a new entry for `v2.7.1` to the `only` block in the `master` AppVeyor config.
  * We generally want to update master instead of editing the `appveyor.yaml` in the branch to avoid merge conflicts if `v2.7.1` is merged back in.
* Submit the `appveyor.yaml` change to `master`
* Create branch `v2.7.1`

Now any changes pushed to `v2.7.1` should get built using the updated config.

**Pull request merged**
